default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: connect123
  host: localhost
  

development:
  <<: *default
  database: dia-de-treinamento_development

test:
  <<: *default
  database: dia-de-treinamento_test

production:
  <<: *default
  database: dia-de-treinamento
  pool: 10