default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: Secret ;)
  host: localhost

development:
  <<: *default
  database: dia-de-treinamento_development

test:
  <<: *default
  database: dia-de-treinamento_test

production:
  <<: *default
  username: diadetreinamento
  password: 'Secret :)'
  database: dia-de-treinamento
  pool: 2
