defaults: &defaults
  host: localhost
  username: postgres
  password: connect123
  template: template0
  encoding: utf8
  pool: 5
  adapter: postgresql

development:
  database: dia-de-treinamento_development
  <<: *defaults

test:
  database: dia-de-treinamento_test
  min_messages: WARNING
  <<: *defaults

production:
  <<: *defaults
  database: dia-de-treinamento
  password: <%= ENV['DB_ENV_POSTGRES_PASSWORD'] %>
  host: db
